project:
  type: book
  post-render:
    - scripts/fix_links.py
    - scripts/fix_search_highlight.py

date-format: "MMMM D, YYYY"

book:
  title: "Doctrinal Declarations of Evangel Presbytery"
  author: "Evangel Presbytery"
  subtitle: "Amended June 5, 2025"
  repo-url: https://github.com/Evangel-Presbytery/evangel-ddp
  chapters:
    - index.qmd
    - 01-Declaration-of-Doctrine-on-Sexuality.qmd
    - 02-Declaration-of-Doctrine-on-Abortion.qmd
    - 07-Updates.qmd
  sidebar:
    header: TOCheader.qmd
    search: true
  favicon: "evangel-favicon-196.png"
  navbar: 
    title: false
    logo: logo-white.png
    logo-href: https://evangelpresbytery.com
    search: false
    left:
      - text: Book of Church Order
        href: https://bco.evangelpresbytery.com
      - text: Doctrinal Declarations
        href: https://ddp.evangelpresbytery.com
      - text: Bylaws
        href: https://bylaws.evangelpresbytery.com

format:
  html:
    number-sections: false
    css: 
      - evangel-docs-global.css
      - ddp.css
    toc-location: left
    include-in-header: in_header.html
  pdf:
    pdf-engine: xelatex
    documentclass: scrreprt
    toc: true
    toc-title: Table of Contents
    toc-depth: 2
    number-sections: false
    include-in-header:
      - evangel-docs-global.tex
      - ddp.tex
